from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime
from io import StringIO
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TWSE_BROKER_DIR = PROJECT_ROOT / "data" / "broker" / "twse"
DEFAULT_BY_STOCK_DIR = TWSE_BROKER_DIR / "by_stock"
DEFAULT_BY_BROKER_DIR = TWSE_BROKER_DIR / "by_broker"
DEFAULT_METADATA_PATH = PROJECT_ROOT / "data" / "metadata.csv"
DEFAULT_LOG_DIR = PROJECT_ROOT / "logs" / "broker"

RAW_NAME_RE = re.compile(r"^(?P<code>\d{4,6})_bsr_twse_(?P<date>\d{8})_.*\.csv$")
INVALID_FILENAME_CHARS_RE = re.compile(r'[\\/:*?"<>|]+')
RESERVED_WINDOWS_FILENAMES = {
    "CON",
    "PRN",
    "AUX",
    "NUL",
    *(f"COM{index}" for index in range(1, 10)),
    *(f"LPT{index}" for index in range(1, 10)),
}
OUTPUT_COLUMNS = [
    "Date",
    "Code",
    "Name",
    "券商",
    "價格",
    "買進股數",
    "賣出股數",
    "序號",
    "來源檔案",
]


@dataclass
class BuildStats:
    source_files: int = 0
    parsed_files: int = 0
    skipped_files: int = 0
    output_files: int = 0
    records: int = 0
    migrated_files: int = 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert TWSE BSR per-stock raw CSVs into one CSV per broker."
    )
    parser.add_argument("--twse-dir", type=Path, default=TWSE_BROKER_DIR)
    parser.add_argument("--by-stock-dir", type=Path, default=DEFAULT_BY_STOCK_DIR)
    parser.add_argument("--by-broker-dir", type=Path, default=DEFAULT_BY_BROKER_DIR)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_METADATA_PATH)
    parser.add_argument(
        "--migrate-root-raw",
        action="store_true",
        help="Move root-level twse raw CSVs into by_stock before converting.",
    )
    parser.add_argument(
        "--keep-existing",
        action="store_true",
        help="Do not remove existing generated by_broker CSVs before writing.",
    )
    parser.add_argument(
        "--summary-json",
        type=Path,
        default=None,
        help="Summary JSON path. Default: logs/broker/twse_by_broker_build_<timestamp>.json",
    )
    return parser.parse_args()


def timestamp() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def parse_file_date(value: str) -> str:
    return f"{value[:4]}-{value[4:6]}-{value[6:8]}"


def decode_text(path: Path) -> tuple[str, str]:
    raw = path.read_bytes()
    for encoding in ("cp950", "big5", "utf-8-sig", "utf-8"):
        try:
            return raw.decode(encoding), encoding
        except UnicodeDecodeError:
            continue
    return raw.decode("cp950", errors="replace"), "cp950-replace"


def normalize_broker_name(value: str) -> str:
    return re.sub(r"\s+", "", str(value or "").replace("\u3000", "")).strip()


def safe_filename_part(value: str) -> str:
    cleaned = INVALID_FILENAME_CHARS_RE.sub("_", value).strip().strip(".")
    cleaned = re.sub(r"\s+", "_", cleaned)
    if not cleaned:
        cleaned = "Unknown"
    if cleaned.upper() in RESERVED_WINDOWS_FILENAMES:
        cleaned = f"_{cleaned}"
    return cleaned


def output_path_for_broker(broker: str, used_names: dict[str, str], output_dir: Path) -> Path:
    base = safe_filename_part(broker)
    if base in used_names and used_names[base] != broker:
        digest = hashlib.sha1(broker.encode("utf-8")).hexdigest()[:8]
        base = f"{base}_{digest}"
    used_names[base] = broker
    return output_dir / f"{base}.csv"


def clean_number(value: Any, default: str = "0") -> str:
    text = str(value or "").strip().replace(",", "")
    return text if text else default


def load_metadata_names(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if not reader.fieldnames or "Code" not in reader.fieldnames or "Name" not in reader.fieldnames:
            return {}
        return {
            str(row.get("Code", "")).strip(): str(row.get("Name", "")).strip()
            for row in reader
            if str(row.get("Code", "")).strip()
        }


def root_raw_paths(twse_dir: Path) -> list[Path]:
    return sorted(path for path in twse_dir.glob("*_bsr_twse_*.csv") if path.is_file())


def migrate_root_raw_files(twse_dir: Path, by_stock_dir: Path) -> int:
    paths = root_raw_paths(twse_dir)
    if not paths:
        by_stock_dir.mkdir(parents=True, exist_ok=True)
        return 0

    resolved_twse = twse_dir.resolve()
    resolved_by_stock = by_stock_dir.resolve()
    if resolved_by_stock.parent != resolved_twse:
        raise ValueError(f"Refusing to migrate raw files outside {resolved_twse}: {resolved_by_stock}")

    by_stock_dir.mkdir(parents=True, exist_ok=True)
    moved = 0
    for path in paths:
        target = by_stock_dir / path.name
        if target.exists():
            if target.stat().st_size != path.stat().st_size:
                raise FileExistsError(f"Migration target already exists with different size: {target}")
            path.unlink()
        else:
            shutil.move(str(path), str(target))
        moved += 1
    return moved


def raw_paths(by_stock_dir: Path) -> list[Path]:
    return sorted(path for path in by_stock_dir.glob("*_bsr_twse_*.csv") if path.is_file())


def iter_trade_records(path: Path, metadata_names: dict[str, str]) -> tuple[list[dict[str, str]], dict[str, Any]]:
    match = RAW_NAME_RE.match(path.name)
    if not match:
        return [], {"path": str(path), "reason": "filename_not_recognized"}

    code = match.group("code")
    date_text = parse_file_date(match.group("date"))
    name = metadata_names.get(code, "")
    text, encoding = decode_text(path)
    records: list[dict[str, str]] = []

    for row in csv.reader(StringIO(text)):
        for offset in (0, 6):
            if len(row) < offset + 5:
                continue
            sequence = str(row[offset]).strip()
            if not sequence.isdigit():
                continue
            broker = normalize_broker_name(row[offset + 1])
            if not broker:
                continue
            records.append(
                {
                    "Date": date_text,
                    "Code": code,
                    "Name": name,
                    "券商": broker,
                    "價格": clean_number(row[offset + 2], default=""),
                    "買進股數": clean_number(row[offset + 3]),
                    "賣出股數": clean_number(row[offset + 4]),
                    "序號": sequence,
                    "來源檔案": path.name,
                }
            )

    return records, {"path": str(path), "encoding": encoding, "records": len(records)}


def clean_output_dir(output_dir: Path) -> int:
    if not output_dir.exists():
        output_dir.mkdir(parents=True, exist_ok=True)
        return 0
    removed = 0
    for path in output_dir.glob("*.csv"):
        path.unlink()
        removed += 1
    return removed


def write_by_broker(records_by_broker: dict[str, list[dict[str, str]]], output_dir: Path) -> int:
    output_dir.mkdir(parents=True, exist_ok=True)
    used_names: dict[str, str] = {}
    written = 0
    for broker in sorted(records_by_broker):
        records = sorted(
            records_by_broker[broker],
            key=lambda row: (row["Date"], row["Code"], float(row["價格"] or 0), int(row["序號"])),
        )
        output_path = output_path_for_broker(broker, used_names, output_dir)
        with output_path.open("w", encoding="utf-8-sig", newline="") as handle:
            writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS)
            writer.writeheader()
            writer.writerows(records)
        written += 1
    return written


def build_outputs(args: argparse.Namespace) -> dict[str, Any]:
    stats = BuildStats()
    if args.migrate_root_raw:
        stats.migrated_files = migrate_root_raw_files(args.twse_dir, args.by_stock_dir)
    else:
        args.by_stock_dir.mkdir(parents=True, exist_ok=True)

    metadata_names = load_metadata_names(args.metadata)
    records_by_broker: dict[str, list[dict[str, str]]] = defaultdict(list)
    skipped: list[dict[str, Any]] = []
    parsed: list[dict[str, Any]] = []

    paths = raw_paths(args.by_stock_dir)
    stats.source_files = len(paths)
    for path in paths:
        records, info = iter_trade_records(path, metadata_names)
        if records:
            stats.parsed_files += 1
            stats.records += len(records)
            for record in records:
                records_by_broker[record["券商"]].append(record)
            parsed.append(info)
        else:
            stats.skipped_files += 1
            skipped.append(info)

    removed_existing = 0 if args.keep_existing else clean_output_dir(args.by_broker_dir)
    stats.output_files = write_by_broker(records_by_broker, args.by_broker_dir)

    summary_path = args.summary_json
    if summary_path is None:
        summary_path = DEFAULT_LOG_DIR / f"twse_by_broker_build_{timestamp()}.json"
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary = {
        "stats": asdict(stats),
        "by_stock_dir": str(args.by_stock_dir),
        "by_broker_dir": str(args.by_broker_dir),
        "removed_existing_by_broker_files": removed_existing,
        "summary_json": str(summary_path),
        "skipped": skipped,
        "parsed_sample": parsed[:10],
    }
    summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    return summary


def main() -> int:
    summary = build_outputs(parse_args())
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
